### ISSUE TITLE
Visualizing result

### ISSUE THREAD

**Issue by varun365** [edwardzhou130/PolarSeg#11]
Hi @edwardzhou130 @YangZhang4065 

I have generated the predictions from pretrained model and used the https://github.com/PRBonn/semantic-kitti-api to visualize the result
IOU is as follows
class iou: 
car : 90.11%
bicycle : 37.91%
motorcycle : 0.14%
truck : 0.00%
bus : 30.64%
person : 48.71%
bicyclist : 82.20%
motorcyclist : 0.00%
road : 96.21%
parking : 34.88%
sidewalk : 85.71%
other-ground : 0.12%
building : 92.32%
fence : 26.77%
vegetation : 81.96%
trunk : 69.04%
terrain : 76.29%
pole : 64.89%
traffic-sign : 28.24%
the visualized result is
![000001](https://user-images.githubusercontent.com/30046668/81524476-fab3e280-936e-11ea-937c-25fc5b397301.png)

1. Observed that the label colors are different in the image and vegetation is not detected or of different label, is there any other method to visualize the generated predictions
2. What are the changes to be made to train for less no of classes

Thanks for your effort and replies.

**Comment by edwardzhou130** [comment]
1. The color problem is likely due to the label number mismatch. You need to map the label back to its original format. Here is the mapping dictionary:
https://github.com/edwardzhou130/PolarSeg/blob/73488e8fe3ea9505d2822232ac5e814530c3c724/semantic-kitti.yaml#L144-L164
[semantic-kitti-api](https://github.com/PRBonn/semantic-kitti-api) provides a script to do this mapping (add ``--inverse``): https://github.com/PRBonn/semantic-kitti-api/blob/master/remap_semantic_labels.py

2. You can refer to #2 for training with fewer classes.

**Comment by varun365** [comment]
thanks @edwardzhou130 will check that
