### ISSUE TITLE
torch_catter.scatter_max ()

### ISSUE THREAD

**Issue by yangchandler** [edwardzhou130/PolarSeg#28]
Hello, thank you very much for your open source code.

Now I'm trying to convert your code using libtorch, but I run into a tricky problem.

The torch_catter.scatter_max () function cannot be used directly by LibTorch because it uses a dynamic library. I tried to search for the specific meaning of this function, but unfortunately I couldn't find it.

Could you please help to explain the specific function of this function when you have time?

Thank you!!!

**Comment by YangZhang4065** [comment]
Hi @yangchandler ,

Thank you for your interest in the repo! torch_catter.scatter_max () serves a very crucial step in our model. You probably have already seen this but the doc of the function is here: https://pytorch-scatter.readthedocs.io/en/1.3.0/functions/max.html

The purpose of this function is to max-pool an arbitrary number of point representations input into a fixed 2D grid representation. Using scatter_max will allows us to parallelly pool any number of points, instead of a fixed number of points, with high efficiency.

eq. (1) in https://arxiv.org/pdf/2003.14032.pdf exactly describe what the function does with more details.

If you want to convert the model using libtorch, the best bet is to see if there is any official PyTorch substation for this function yet.

**Comment by edwardzhou130** [comment]
A workaround for the scatter-max is preprocessing the input data as a fixed size tensor by padding zeros to the empty space.
